<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * @deprecated
 * Legacy seeder. Do not call from DatabaseSeeder.
 */
class EngineeringSkillsSeeder extends Seeder
{
    public function run(): void
    {
        // ─────────────────────────────────────────────────────────────────
        // Subdomain lookup is scoped by parent domain name so that
        // duplicate subdomain names (e.g. "پلیمر", "محیط زیست") resolve
        // to the correct row for each domain.
        // ─────────────────────────────────────────────────────────────────
        $taxonomy = [

            // ── مهندسی برق ───────────────────────────────────────────────
            'مهندسی برق' => [
                'ابزاردقیق' => [
                    'LabVIEW',
                    'MATLAB',
                    'Siemens TIA Portal',
                    'AVEVA PI System (OSIsoft PI)',
                    'Kepware KEPServerEX',
                    'Ignition (Inductive Automation)',
                    'Wonderware InTouch',
                    'Honeywell Experion PKS',
                    'Emerson DeltaV',
                    'Yokogawa CENTUM VP',
                    'ABB 800xA',
                    'National Instruments DIAdem',
                    'SIMATIC WinCC',
                    'PTC ThingWorx',
                    'OPC-UA Toolkits',
                ],
                'الکترونیک' => [
                    'Altium Designer',
                    'KiCad',
                    'Eagle (Autodesk)',
                    'Cadence OrCAD',
                    'Cadence Allegro PCB',
                    'LTspice',
                    'Multisim (NI)',
                    'Proteus Design Suite',
                    'PSpice',
                    'Cadence Virtuoso',
                    'Mentor PADS',
                    'Zuken CR-8000',
                    'ANSYS HFSS',
                    'CST Studio Suite',
                    'Keysight ADS',
                ],
                'الکترونیک قدرت' => [
                    'PSIM',
                    'PLECS',
                    'LTspice',
                    'MATLAB/Simulink Power Systems',
                    'PSCAD',
                    'EMTP-RV',
                    'ANSYS Maxwell',
                    'Altair Flux',
                    'Saber (Synopsys)',
                    'GeckoCIRCUITS',
                    'SIMetrix',
                    'Altium Designer',
                    'ETAP',
                    'DIgSILENT PowerFactory',
                    'Cadence PSpice',
                ],
                'سیستم‌های دیجیتال' => [
                    'Xilinx Vivado',
                    'Intel Quartus Prime',
                    'ModelSim (Mentor)',
                    'Questa (Siemens EDA)',
                    'Synopsys Design Compiler',
                    'Cadence Genus',
                    'MATLAB HDL Toolbox',
                    'Aldec Active-HDL',
                    'Icarus Verilog',
                    'Verilator',
                    'Synopsys VCS',
                    'Cadence Xcelium',
                    'GHDL',
                    'Tanner EDA',
                    'Xilinx Vitis HLS',
                ],
                'قدرت' => [
                    'ETAP',
                    'DIgSILENT PowerFactory',
                    'PSS/E (Siemens PTI)',
                    'PSCAD',
                    'PowerWorld Simulator',
                    'NEPLAN',
                    'SKM Power*Tools',
                    'CYME',
                    'EMTP-ATP',
                    'MATLAB Power System Toolbox',
                    'OpenDSS',
                    'CDEGS',
                    'DigSILENT',
                    'CYMGRD',
                    'ABB Network Manager',
                ],
                'کنترل' => [
                    'MATLAB/Simulink',
                    'LabVIEW',
                    'Siemens TIA Portal',
                    'Allen-Bradley Studio 5000',
                    'Beckhoff TwinCAT',
                    'AVEVA System Platform',
                    'Wonderware InTouch',
                    'Ignition (Inductive Automation)',
                    'SIMATIC WinCC',
                    'Rockwell FactoryTalk',
                    'NI VeriStand',
                    'Scilab/Xcos',
                    'OPAL-RT eMEGAsim',
                    'dSPACE',
                    'Automation Studio (Famic)',
                ],
                'مخابرات' => [
                    'MATLAB Communications Toolbox',
                    'Keysight ADS',
                    'CST Studio Suite',
                    'ANSYS HFSS',
                    'AWR Microwave Office',
                    'FEKO (Altair)',
                    'Remcom XFdtd',
                    'GRASP (Ticra)',
                    'SystemVue (Keysight)',
                    'Keysight SystemVue',
                    'GNU Radio',
                    'OPNET Modeler (Riverbed)',
                    'NS-3',
                    'GNS3',
                    'Wireshark',
                ],
                'مهندسی پزشکی برق' => [
                    'MATLAB (Biomedical Toolbox)',
                    'LabVIEW',
                    'EEGLAB',
                    'MNE-Python',
                    'SPM (Statistical Parametric Mapping)',
                    'BrainVision Analyzer',
                    'FieldTrip',
                    'OpenBCI',
                    'COMSOL Multiphysics',
                    'ANSYS HFSS',
                    'CST Studio Suite',
                    'Altium Designer',
                    'BIOPAC Systems Software',
                    'NeuroScan',
                    'BrainSuite',
                ],
            ],

            // ── مهندسی پزشکی (بیومدیکال) ────────────────────────────────
            'مهندسی پزشکی (بیومدیکال)' => [
                'بافت' => [
                    'COMSOL Multiphysics',
                    'MATLAB',
                    'Abaqus/CAE',
                    'ANSYS Mechanical',
                    'SolidWorks',
                    'Materialise Mimics',
                    '3-matic (Materialise)',
                    'ImageJ / Fiji',
                    'IMARIS',
                    'CellProfiler',
                    'Amira (Thermo Fisher)',
                    'ZEN (Zeiss)',
                    'BioRender',
                    'Autodesk Fusion 360',
                    'FlexPDE',
                ],
                'بیوالکتریک' => [
                    'MATLAB',
                    'LabVIEW',
                    'COMSOL Multiphysics',
                    'EEGLAB',
                    'MNE-Python',
                    'SPM12',
                    'BrainSuite',
                    'FSL (FMRIB Software Library)',
                    'FreeSurfer',
                    'ANSYS HFSS',
                    'SimBio',
                    'BioSig',
                    'OpenBCI',
                    'Altium Designer',
                    '4D-RCS',
                ],
                'بیومکانیک' => [
                    'OpenSim',
                    'AnyBody Modeling System',
                    'ANSYS Mechanical',
                    'Abaqus/CAE',
                    'COMSOL Multiphysics',
                    'MSC Adams',
                    'LifeMOD',
                    'Visual3D',
                    'Vicon Nexus',
                    'MATLAB',
                    'SolidWorks',
                    'Materialise Mimics',
                    'GaitLab',
                    'SIMM (MusculoGraphics)',
                    'PEEK CAD',
                ],
                'تجهیزات پزشکی' => [
                    'SolidWorks',
                    'PTC Creo',
                    'CATIA',
                    'Siemens NX',
                    'Autodesk Inventor',
                    'ANSYS Mechanical',
                    'COMSOL Multiphysics',
                    'Materialise Mimics',
                    'Altium Designer',
                    'LabVIEW',
                    'MATLAB',
                    'CST Studio Suite',
                    'ANSYS HFSS',
                    'Zuken E3.series',
                    'MagNet (Infolytica)',
                ],
            ],

            // ── مهندسی شهرسازی ───────────────────────────────────────────
            'مهندسی شهرسازی' => [
                'برنامه‌ریزی شهری' => [
                    'ArcGIS',
                    'QGIS',
                    'AutoCAD Civil 3D',
                    'CityEngine (Esri)',
                    'UrbanSim',
                    'ENVI-met',
                    'Lumion',
                    'SketchUp',
                    'Rhino + Grasshopper',
                    'CommunityViz',
                    'INDEX (Collaborative Decision Support)',
                    'Space Syntax Tools',
                    'VISSIM (PTV)',
                    'Bentley MAP',
                    'MapInfo Pro',
                ],
                'برنامه‌ریزی منطقه‌ای' => [
                    'ArcGIS',
                    'QGIS',
                    'TransCAD',
                    'CUBE (Citilabs)',
                    'EMME',
                    'UrbanSim',
                    'GeoDa',
                    'SPSS',
                    'R (statistical)',
                    'CommunityViz',
                    'OpenTripPlanner',
                    'MATLAB',
                    'Bentley MAP',
                    'MapInfo Pro',
                    'Atlas.ti',
                ],
                'ترافیک و حمل‌ونقل' => [
                    'VISSIM (PTV)',
                    'Synchro',
                    'SimTraffic',
                    'AIMSUN',
                    'TransCAD',
                    'CUBE (Citilabs)',
                    'EMME',
                    'VISUM (PTV)',
                    'HCS (Highway Capacity Software)',
                    'SIDRA Intersection',
                    'CORSIM',
                    'MATSim',
                    'SUMO',
                    'Paramics',
                    'SATURN',
                ],
                'طراحی شهری' => [
                    'SketchUp',
                    'Rhino + Grasshopper',
                    'AutoCAD',
                    'Revit',
                    'Lumion',
                    'Twinmotion',
                    'CityEngine (Esri)',
                    'ENVI-met',
                    'ArcGIS',
                    'QGIS',
                    'Adobe Illustrator',
                    'Vectorworks',
                    'Bentley MicroStation',
                    'Autodesk InfraWorks',
                    'Blender',
                ],
            ],

            // ── مهندسی شیمی ──────────────────────────────────────────────
            'مهندسی شیمی' => [
                'بیوشیمی' => [
                    'Aspen Plus',
                    'COMSOL Multiphysics',
                    'MATLAB',
                    'SuperPro Designer',
                    'AutoDock',
                    'GROMACS',
                    'AMBER',
                    'NAMD',
                    'MOE (Chemical Computing Group)',
                    'Schrödinger Suite',
                    'BIOVIA Discovery Studio',
                    'PyMOL',
                    'ChemDraw (PerkinElmer)',
                    'KNIME',
                    'Python (BioPython)',
                ],
                'پلیمر' => [
                    'Aspen Polymers',
                    'ANSYS Polyflow',
                    'COMSOL Multiphysics',
                    'Moldflow (Autodesk)',
                    'Moldex3D',
                    'Abaqus/CAE',
                    'LAMMPS',
                    'GROMACS',
                    'Materials Studio (BIOVIA)',
                    'Thermo-Calc',
                    'Schrödinger',
                    'Aspen Plus',
                    'PRO/II (AVEVA)',
                    'OriginPro',
                    'MATLAB',
                ],
                'فرآیند' => [
                    'Aspen HYSYS',
                    'Aspen Plus',
                    'PRO/II (AVEVA)',
                    'CHEMCAD',
                    'UniSim Design (Honeywell)',
                    'HTRI Xchanger Suite',
                    'SimSci DYNSIM',
                    'MATLAB/Simulink',
                    'COMSOL Multiphysics',
                    'AFT Fathom',
                    'AFT Arrow',
                    'Pipesim (SLB)',
                    'PIPE-FLO',
                    'ProMax (Bryan Research)',
                    'AutoCAD P&ID',
                ],
                'محیط زیست شیمیایی' => [
                    'Aspen Plus',
                    'MATLAB',
                    'COMSOL Multiphysics',
                    'AERMOD (EPA)',
                    'PHREEQC',
                    'WASP (Water Quality)',
                    'HEC-RAS',
                    'MIKE by DHI',
                    'Visual MINTEQ',
                    'MODFLOW',
                    'EPA SWMM',
                    'ArcGIS',
                    'QGIS',
                    'BASINS (EPA)',
                    'HSC Chemistry (Outotec)',
                ],
            ],

            // ── مهندسی صنایع ─────────────────────────────────────────────
            'مهندسی صنایع' => [
                'ایمنی صنعتی' => [
                    'Phast (DNV)',
                    'SAFETI (DNV)',
                    'CANARY (Quest Consultants)',
                    'FRED (GexCon)',
                    'FLACS (GexCon)',
                    'EFFECTS (TNO)',
                    'Bow-TieXP',
                    'PHAWorks',
                    'HAZOP Studio',
                    'AspenTech PHAPRO',
                    'RiskSpectrum',
                    'SafetyBaobab',
                    'RISKCURVES',
                    'IQ-RM Pro (FMEA)',
                    'BowTie software (CGE Risk)',
                ],
                'بهینه‌سازی' => [
                    'IBM CPLEX',
                    'Gurobi',
                    'LINGO',
                    'GAMS',
                    'AMPL',
                    'AIMMS',
                    'Python (PuLP)',
                    'Python (OR-Tools)',
                    'MATLAB Optimization Toolbox',
                    'R (lpSolve)',
                    'OptQuest',
                    'Arena (OptQuest)',
                    'AnyLogic',
                    'Simul8',
                    'Plant Simulation (Siemens)',
                ],
                'تولید' => [
                    'Siemens Tecnomatix Plant Simulation',
                    'Arena (Rockwell)',
                    'AnyLogic',
                    'Witness (Lanner)',
                    'FlexSim',
                    'AutoCAD',
                    'SolidWorks',
                    'CATIA',
                    'Siemens NX',
                    'MasterCAM',
                    'FeatureCAM',
                    'Vericut',
                    'DELMIA (Dassault)',
                    'SAP ERP (Production)',
                    'Oracle NetSuite',
                ],
                'کیفیت' => [
                    'Minitab',
                    'JMP (SAS)',
                    'SigmaXL',
                    'QI Macros',
                    'MATLAB Statistics Toolbox',
                    'R',
                    'Python (SciPy)',
                    'STATISTICA (Tibco)',
                    'SPC for Excel',
                    'Isograph Availability Workbench',
                    'Relyence Studio (FMEA)',
                    'IQ-RM Pro',
                    'Tableau',
                    'Power BI',
                    'GainSeeker Suite',
                ],
                'لجستیک' => [
                    'AnyLogic',
                    'Arena',
                    'FlexSim',
                    'IBM CPLEX',
                    'Gurobi',
                    'SAP EWM',
                    'Oracle Transportation Management',
                    'Manhattan Associates WMS',
                    'TransCAD',
                    'OpenTripPlanner',
                    'MATLAB',
                    'Python (OR-Tools)',
                    'ArcGIS (routing)',
                    'Routific',
                    'OptimoRoute',
                ],
            ],

            // ── مهندسی عمران ─────────────────────────────────────────────
            'مهندسی عمران' => [
                'آب و هیدرولیک' => [
                    'HEC-RAS',
                    'HEC-HMS',
                    'EPA SWMM',
                    'MIKE FLOOD (DHI)',
                    'MIKE URBAN (DHI)',
                    'EPANET',
                    'WaterGEMS (Bentley)',
                    'WaterCAD (Bentley)',
                    'SewerGEMS (Bentley)',
                    'XPSWMM',
                    'InfoWorks ICM',
                    'FLOW-3D',
                    'TUFLOW',
                    'SOBEK (Deltares)',
                    'Delft-FEWS',
                ],
                'راه و ترابری' => [
                    'AutoCAD Civil 3D',
                    'Bentley OpenRoads Designer',
                    'Bentley InRoads',
                    'Autodesk InfraWorks',
                    'VISSIM (PTV)',
                    'Synchro',
                    'AIMSUN',
                    'TransCAD',
                    'HCS (Highway Capacity Software)',
                    'SIDRA Intersection',
                    'RoadEng (Softree)',
                    'PLAXIS (pavement)',
                    'Navisworks',
                    'MX Roads (Bentley)',
                    'CORSIM',
                ],
                'زلزله' => [
                    'SeismoStruct',
                    'SeismoSignal',
                    'SeismoMatch',
                    'OpenSees',
                    'ETABS',
                    'SAP2000',
                    'ANSYS Mechanical',
                    'ABAQUS',
                    'PERFORM-3D',
                    'IDARC-2D',
                    'Zeus-NL',
                    'Ruaumoko',
                    'DRAIN-2DX',
                    'QUAKE/W (GeoStudio)',
                    'HAZUS (FEMA)',
                ],
                'ژئوتکنیک' => [
                    'PLAXIS 2D',
                    'PLAXIS 3D',
                    'GEO5',
                    'SLOPE/W (GeoStudio)',
                    'SEEP/W (GeoStudio)',
                    'SIGMA/W (GeoStudio)',
                    'SETTLE3',
                    'FLAC (Itasca)',
                    'FLAC3D (Itasca)',
                    'PFC (Itasca)',
                    'Rocscience RS2',
                    'Rocscience RS3',
                    'Slide2 (Rocscience)',
                    'Slide3 (Rocscience)',
                    'RocFall',
                    'LPile',
                    'AllPile',
                    'DEEPXCAV',
                    'GRLWEAP',
                    'FB-MultiPier',
                ],
                'سازه' => [
                    'ETABS',
                    'SAP2000',
                    'SAFE',
                    'CSiBridge',
                    'Tekla Structures',
                    'STAAD.Pro',
                    'Robot Structural Analysis (RSA)',
                    'ABAQUS',
                    'ANSYS Mechanical',
                    'RISA-3D',
                    'RAM Structural System',
                    'IDEA StatiCa',
                    'SkyCiv',
                    'RFEM (Dlubal)',
                    'MIDAS Gen',
                    'Revit Structure',
                    'SeismoStruct',
                    'PERFORM-3D',
                    'SOFiSTiK',
                    'MIDAS Civil',
                ],
                'محیط زیست' => [
                    'AERMOD (EPA)',
                    'CALPUFF',
                    'MIKE by DHI',
                    'HEC-RAS',
                    'EPA SWMM',
                    'MODFLOW',
                    'MT3DMS',
                    'PHREEQC',
                    'Visual MODFLOW',
                    'GMS (Groundwater Modeling System)',
                    'FEFLOW (DHI)',
                    'BASINS (EPA)',
                    'ArcGIS',
                    'QGIS',
                    'WASP',
                ],
                'مدیریت ساخت' => [
                    'Primavera P6',
                    'MS Project',
                    'Procore',
                    'Autodesk BIM 360',
                    'Navisworks',
                    'Revit',
                    'Tekla Structures',
                    'ASTA Powerproject',
                    'Oracle Aconex',
                    'Synchro Pro',
                    'RIB iTWO',
                    'Candy (CCS)',
                    'Exactal CostX',
                    'Bluebeam Revu',
                    'PlanGrid',
                ],
            ],

            // ── مهندسی کامپیوتر ──────────────────────────────────────────
            'مهندسی کامپیوتر' => [
                'امنیت' => [
                    'Wireshark',
                    'Nmap',
                    'Metasploit',
                    'Burp Suite',
                    'OWASP ZAP',
                    'Nessus',
                    'Qualys',
                    'Kali Linux',
                    'Snort',
                    'Splunk',
                    'IBM QRadar',
                    'CrowdStrike Falcon',
                    'Carbon Black',
                    'Tenable.io',
                    'Volatility (forensics)',
                ],
                'داده' => [
                    'Python (pandas / NumPy)',
                    'R',
                    'Apache Spark',
                    'Hadoop',
                    'Tableau',
                    'Power BI',
                    'Apache Kafka',
                    'Databricks',
                    'Alteryx',
                    'SAS',
                    'KNIME',
                    'dbt',
                    'Apache Airflow',
                    'MongoDB',
                    'PostgreSQL',
                ],
                'سخت‌افزار' => [
                    'Xilinx Vivado',
                    'Intel Quartus Prime',
                    'ModelSim',
                    'Cadence Virtuoso',
                    'Synopsys Design Compiler',
                    'Altium Designer',
                    'KiCad',
                    'LTspice',
                    'ANSYS HFSS',
                    'ARM Development Studio',
                    'IAR Embedded Workbench',
                    'Keil MDK',
                    'STM32CubeIDE',
                    'PlatformIO',
                    'Xilinx Vitis HLS',
                ],
                'شبکه' => [
                    'Cisco Packet Tracer',
                    'GNS3',
                    'EVE-NG',
                    'Wireshark',
                    'SolarWinds NPM',
                    'PRTG Network Monitor',
                    'Nagios',
                    'Zabbix',
                    'Ansible',
                    'VMware vSphere',
                    'pfSense',
                    'OpenDaylight (SDN)',
                    'NS-3',
                    'OPNET (Riverbed Modeler)',
                    'Terraform',
                ],
                'نرم‌افزار' => [
                    'Visual Studio Code',
                    'IntelliJ IDEA',
                    'Eclipse',
                    'Git / GitHub / GitLab',
                    'Docker',
                    'Kubernetes',
                    'Jenkins',
                    'GitHub Actions',
                    'Jira',
                    'SonarQube',
                    'Android Studio',
                    'Xcode',
                    'Postman',
                    'Enterprise Architect (UML)',
                    'JUnit / Selenium',
                ],
                'هوش مصنوعی' => [
                    'TensorFlow',
                    'PyTorch',
                    'Keras',
                    'Scikit-learn',
                    'Jupyter Notebook',
                    'MATLAB Deep Learning Toolbox',
                    'Hugging Face Transformers',
                    'Weights & Biases',
                    'MLflow',
                    'KNIME',
                    'RapidMiner',
                    'Weka',
                    'LabelImg / CVAT',
                    'Roboflow',
                    'NVIDIA CUDA / cuDNN',
                ],
            ],

            // ── مهندسی متالورژی و مواد ───────────────────────────────────
            'مهندسی متالورژی و مواد' => [
                'پلیمر' => [
                    'Aspen Polymers',
                    'Moldflow (Autodesk)',
                    'Moldex3D',
                    'ANSYS Polyflow',
                    'COMSOL Multiphysics',
                    'Materials Studio (BIOVIA)',
                    'Abaqus/CAE',
                    'LAMMPS',
                    'GROMACS',
                    'Thermo-Calc',
                    'JMatPro',
                    'OriginPro',
                    'TA Instruments TRIOS',
                    'SigmaPlot',
                    'MATLAB',
                ],
                'خوردگی' => [
                    'OLI Studio',
                    'Elsyca CorrosionMaster',
                    'COMSOL Multiphysics',
                    'ANSYS Fluent',
                    'Thermo-Calc',
                    'FactSage',
                    'EC-Lab (Bio-Logic)',
                    'JMatPro',
                    'MATLAB',
                    'R',
                    'OriginPro',
                    'AutoCAD (piping)',
                    'Corrdata',
                    'PHREEQC',
                    'Python',
                ],
                'سرامیک' => [
                    'COMSOL Multiphysics',
                    'ANSYS Mechanical',
                    'Abaqus/CAE',
                    'Materials Studio (BIOVIA)',
                    'Thermo-Calc',
                    'FactSage',
                    'VESTA (crystal structure)',
                    'CrystalMaker',
                    'Diamond (crystal & molecular)',
                    'JADE (XRD analysis)',
                    'TOPAS (Bruker)',
                    'OriginPro',
                    'ImageJ',
                    'MATLAB',
                    'Python',
                ],
                'فلزات' => [
                    'Thermo-Calc',
                    'JMatPro',
                    'DEFORM (metal forming)',
                    'FORGE (Transvalor)',
                    'AutoForm',
                    'Abaqus/CAE',
                    'ANSYS Mechanical',
                    'COMSOL Multiphysics',
                    'FactSage',
                    'ProCAST (casting)',
                    'MAGMASOFT',
                    'OptiCast',
                    'OriginPro',
                    'MATLAB',
                    'Python',
                ],
                'نانومواد' => [
                    'Materials Studio (BIOVIA)',
                    'LAMMPS',
                    'GROMACS',
                    'NAMD',
                    'VASP',
                    'Quantum ESPRESSO',
                    'Gaussian',
                    'COMSOL Multiphysics',
                    'VMD (Visual Molecular Dynamics)',
                    'VESTA',
                    'CrystalMaker',
                    'Gwyddion (SPM analysis)',
                    'ImageJ / Fiji',
                    'OriginPro',
                    'Avogadro',
                ],
            ],

            // ── مهندسی محیط زیست ─────────────────────────────────────────
            'مهندسی محیط زیست' => [
                'آب و فاضلاب' => [
                    'EPANET',
                    'WaterGEMS (Bentley)',
                    'SewerGEMS (Bentley)',
                    'EPA SWMM',
                    'InfoWorks ICM',
                    'MIKE URBAN (DHI)',
                    'MIKE FLOOD (DHI)',
                    'AQUASIM',
                    'GPS-X (Hydromantis)',
                    'BioWin (EnviroSim)',
                    'HEC-RAS',
                    'PHREEQC',
                    'ArcGIS',
                    'QGIS',
                    'MATLAB',
                ],
                'ارزیابی زیست‌محیطی' => [
                    'AERMOD (EPA)',
                    'CALPUFF',
                    'SCREEN3 (EPA)',
                    'ADMS (CERC)',
                    'SimaPro',
                    'openLCA',
                    'GaBi (Sphera)',
                    'TRACI (USEPA)',
                    'CML-IA (Leiden)',
                    'ArcGIS',
                    'QGIS',
                    'MIKE by DHI',
                    'MODFLOW',
                    'HEC-RAS',
                    'MATLAB',
                ],
                'پسماند' => [
                    'SimaPro',
                    'openLCA',
                    'GaBi (Sphera)',
                    'Umberto NXT (ifu Hamburg)',
                    'WRATE',
                    'ORWARE',
                    'MSW-DST (EPA)',
                    'ArcGIS',
                    'QGIS',
                    'FlexSim',
                    'AnyLogic',
                    'EPA SWMM',
                    'AERMOD (EPA)',
                    'MATLAB',
                    'Python',
                ],
                'هوا' => [
                    'AERMOD (EPA)',
                    'CALPUFF',
                    'CMAQ (EPA)',
                    'CAMx',
                    'ADMS (CERC)',
                    'SCREEN3 (EPA)',
                    'WRF (Weather Research & Forecasting)',
                    'HYSPLIT (NOAA)',
                    'MOVES (EPA)',
                    'COPERT',
                    'R (openair package)',
                    'ArcGIS',
                    'MATLAB',
                    'Python',
                    'EnergyPLAN',
                ],
            ],

            // ── مهندسی معدن ──────────────────────────────────────────────
            'مهندسی معدن' => [
                'استخراج' => [
                    'Datamine Studio OP',
                    'Vulcan (Maptek)',
                    'Surpac (Dassault)',
                    'MineSight (Hexagon)',
                    'Deswik Suite',
                    'Minesched',
                    'Whittle (Datamine)',
                    'JKSimBlast',
                    'ShotPlus (Orica)',
                    'FLAC (Itasca)',
                    'Rocscience RS2',
                    'AutoCAD',
                    'ArcGIS',
                    'Leapfrog Geo (Seequent)',
                    'ANSYS Mechanical',
                ],
                'اکتشاف' => [
                    'Leapfrog Geo (Seequent)',
                    'Surpac (Dassault)',
                    'Datamine Studio RM',
                    'GEOSOFT Oasis montaj',
                    'Petrel (SLB)',
                    'Micromine',
                    'ArcGIS',
                    'QGIS',
                    'ENVI (remote sensing)',
                    'ERMapper',
                    'MapInfo',
                    'OpendTect',
                    'Kingdom Suite (IHS)',
                    'MATLAB',
                    'Python',
                ],
                'ژئومکانیک' => [
                    'FLAC (Itasca)',
                    'FLAC3D (Itasca)',
                    'UDEC (Itasca)',
                    '3DEC (Itasca)',
                    'PFC (Itasca)',
                    'Rocscience RS2',
                    'Rocscience RS3',
                    'PLAXIS 3D',
                    'EXAMINE3D (Rocscience)',
                    'Map3D',
                    'ABAQUS',
                    'ANSYS Mechanical',
                    'Slide2 (Rocscience)',
                    'UNWEDGE (Rocscience)',
                    'Phase2 (RS2)',
                ],
                'فرآوری' => [
                    'JKSimMet',
                    'METSIM',
                    'USIM PAC',
                    'HSC Chemistry (Outotec)',
                    'Aspen Plus',
                    'Limn (flowsheet processor)',
                    'MODSIM',
                    'MATLAB',
                    'FactSage',
                    'Metso Bruno (crushing)',
                    'AutoCAD',
                    'SolidWorks',
                    'COMSOL Multiphysics',
                    'Python',
                    'OriginPro',
                ],
            ],

            // ── مهندسی معماری ────────────────────────────────────────────
            'مهندسی معماری' => [
                'مرمت بناها' => [
                    'AutoCAD',
                    'Revit',
                    'SketchUp',
                    'ArchiCAD',
                    'Rhinoceros',
                    'Autodesk ReCap',
                    'Agisoft Metashape',
                    'CloudCompare',
                    'Leica Cyclone (3D scanning)',
                    'BricsCAD BIM',
                    'Lumion',
                    'Twinmotion',
                    'DIANA FEA',
                    'Bentley MicroStation',
                    '3D scanning (FARO Scene)',
                ],
                'معماری' => [
                    'Revit',
                    'ArchiCAD',
                    'AutoCAD',
                    'SketchUp',
                    'Rhinoceros',
                    'Grasshopper',
                    'Lumion',
                    'Twinmotion',
                    'V-Ray',
                    '3ds Max',
                    'Cinema 4D',
                    'Enscape',
                    'Vectorworks',
                    'Bentley MicroStation',
                    'BIMx',
                ],
                'معماری داخلی' => [
                    'AutoCAD',
                    'SketchUp',
                    'Revit',
                    '3ds Max',
                    'V-Ray',
                    'Lumion',
                    'Twinmotion',
                    'Enscape',
                    'Rhinoceros',
                    'ArchiCAD',
                    'Chief Architect',
                    'Planner 5D',
                    'Vectorworks',
                    'Cinema 4D',
                    'Blender',
                ],
                'معماری منظر' => [
                    'AutoCAD',
                    'SketchUp',
                    'Rhinoceros',
                    'Grasshopper',
                    'Lumion',
                    'Twinmotion',
                    'ArcGIS',
                    'QGIS',
                    'AutoCAD Civil 3D',
                    'Land F/X',
                    'Vectorworks Landmark',
                    'ENVI-met',
                    'Autodesk InfraWorks',
                    'Autodesk Forma',
                    'Adobe Illustrator',
                ],
            ],

            // ── مهندسی مکانیک ────────────────────────────────────────────
            'مهندسی مکانیک' => [
                'ارتعاشات' => [
                    'MATLAB/Simulink',
                    'ANSYS Mechanical',
                    'ABAQUS',
                    'MSC Nastran',
                    'Simcenter Testlab (Siemens)',
                    'LMS Test.Lab',
                    'COMSOL Multiphysics',
                    'Romax (Hexagon)',
                    'ANSYS nCode DesignLife',
                    'AVL Excite',
                    'ME\'scopeVES',
                    'PULSE (Brüel & Kjær)',
                    'ACTRAN (MSC)',
                    'OptiStruct (Altair)',
                    'Simcenter 3D (Siemens)',
                ],
                'تبدیل انرژی' => [
                    'MATLAB/Simulink',
                    'ANSYS Fluent',
                    'ANSYS CFX',
                    'EES (Engineering Equation Solver)',
                    'Aspen HYSYS',
                    'Thermoflow THERMOFLEX',
                    'GT-POWER (Gamma Technologies)',
                    'CYCLE-TEMPO',
                    'COMSOL Multiphysics',
                    'Simcenter STAR-CCM+',
                    'OpenFOAM',
                    'REFPROP (NIST)',
                    'TRNSYS',
                    'System Advisor Model (SAM, NREL)',
                    'EnergyPlus',
                ],
                'حرارت و سیال' => [
                    'ANSYS Fluent',
                    'ANSYS CFX',
                    'OpenFOAM',
                    'COMSOL Multiphysics',
                    'Simcenter STAR-CCM+',
                    'SolidWorks Flow Simulation',
                    'FloEFD (Mentor)',
                    'HTRI Xchanger Suite',
                    'AFT Fathom',
                    'EES (Engineering Equation Solver)',
                    'Tecplot 360',
                    'ParaView',
                    'REFPROP (NIST)',
                    'PHOENICS (CHAM)',
                    'FLOW-3D',
                ],
                'ساخت و تولید' => [
                    'SolidWorks',
                    'CATIA',
                    'Siemens NX',
                    'PTC Creo',
                    'AutoCAD',
                    'MasterCAM',
                    'FeatureCAM',
                    'Vericut',
                    'DELMIA (Dassault)',
                    'ABAQUS (forming)',
                    'DEFORM',
                    'AutoForm',
                    'Siemens Tecnomatix',
                    'GibbsCAM',
                    'hyperMILL (OPEN MIND)',
                ],
                'سیالات' => [
                    'ANSYS Fluent',
                    'ANSYS CFX',
                    'OpenFOAM',
                    'COMSOL Multiphysics',
                    'Simcenter STAR-CCM+',
                    'FLOW-3D',
                    'PHOENICS (CHAM)',
                    'SolidWorks Flow Simulation',
                    'AFT Fathom',
                    'AFT Arrow',
                    'Tecplot 360',
                    'ParaView',
                    'SimScale',
                    'EES',
                    'MATLAB',
                ],
                'طراحی جامدات' => [
                    'SolidWorks',
                    'CATIA',
                    'Siemens NX',
                    'PTC Creo',
                    'AutoCAD',
                    'Autodesk Inventor',
                    'ANSYS Mechanical',
                    'ABAQUS',
                    'MSC Nastran',
                    'COMSOL Multiphysics',
                    'OptiStruct (Altair)',
                    'HyperMesh (Altair)',
                    'MATLAB',
                    'RFEM (Dlubal)',
                    'FreeCAD',
                ],
            ],

            // ── مهندسی نفت ───────────────────────────────────────────────
            'مهندسی نفت' => [
                'بهره‌برداری' => [
                    'PROSPER (Petroleum Experts)',
                    'GAP (Petroleum Experts)',
                    'MBAL (Petroleum Experts)',
                    'PIPESIM (SLB)',
                    'OFM (SLB)',
                    'Petrel (SLB)',
                    'Eclipse (SLB)',
                    'KAPPA Workstation',
                    'SAPHIR (KAPPA)',
                    'CMG (Computer Modelling Group)',
                    'tNavigator (RFD)',
                    'Olga (SLB)',
                    'WellFlo',
                    'JewelSuite (Baker Hughes)',
                    'Emeraude (KAPPA)',
                ],
                'حفاری' => [
                    'WellPlan (Halliburton)',
                    'COMPASS (Halliburton)',
                    'Drillworks (Halliburton)',
                    'WELLCAT (Landmark)',
                    'STRESS CHECK (Halliburton)',
                    'Petrel Drilling (SLB)',
                    'DrillBench (SPT)',
                    'OLGA (multiphase)',
                    'Landmark OpenWells',
                    'PERFORM (Landmark)',
                    'Cerberus (NOV)',
                    'BHA design tools',
                    'iEnergy (Halliburton)',
                    'MATLAB',
                    'Python',
                ],
                'خطوط لوله' => [
                    'PIPESIM (SLB)',
                    'OLGA (SLB)',
                    'Synergi Pipeline Simulator (DNV)',
                    'AFT Impulse',
                    'AFT Fathom',
                    'Caesar II',
                    'AutoPIPE (Bentley)',
                    'AVEVA PDMS',
                    'AVEVA E3D',
                    'Smart Plant 3D (Hexagon)',
                    'Aspen HYSYS (pipeline)',
                    'TGNET (gas pipeline)',
                    'SPS (Stoner Pipeline Simulator)',
                    'MATLAB',
                    'Python',
                ],
                'مخزن' => [
                    'Petrel (SLB)',
                    'Eclipse (SLB)',
                    'CMG STARS',
                    'CMG GEM',
                    'CMG IMEX',
                    'INTERSECT (SLB)',
                    'tNavigator (RFD)',
                    'Tempest (Emerson)',
                    'RMS (Emerson)',
                    'KAPPA Workstation',
                    'SAPHIR (KAPPA)',
                    'JewelSuite (Baker Hughes)',
                    'Nexus (Halliburton)',
                    'MATLAB',
                    'Python',
                ],
            ],

            // ── مهندسی نقشه‌برداری ───────────────────────────────────────
            'مهندسی نقشه‌برداری' => [
                'GIS' => [
                    'ArcGIS Pro (Esri)',
                    'QGIS',
                    'ERDAS IMAGINE',
                    'ENVI',
                    'MapInfo Pro',
                    'Bentley MAP',
                    'Global Mapper',
                    'GRASS GIS',
                    'GeoDa',
                    'PostGIS',
                    'SuperGIS (Supergeo)',
                    'Maptitude',
                    'ILWIS',
                    'TerrSet (IDRISI)',
                    'Google Earth Engine',
                ],
                'ژئودزی' => [
                    'Bernese GNSS Software',
                    'GAMIT/GLOBK (MIT)',
                    'GIPSY-OASIS (JPL)',
                    'Trimble Business Center',
                    'Leica Geo Office',
                    'STAR*NET (survey adjustment)',
                    'MicroSurvey FieldGenius',
                    'TOPCON Magnet',
                    'Sokkia Spectrum Survey',
                    'AutoCAD Civil 3D',
                    'NetSurvey',
                    'Global Mapper',
                    'Bentley MicroStation',
                    'GNU Gama',
                    'MATLAB',
                ],
                'سنجش از دور' => [
                    'ENVI',
                    'ERDAS IMAGINE',
                    'eCognition (Trimble)',
                    'ArcGIS Image Analyst',
                    'SNAP (ESA Sentinel Toolbox)',
                    'Google Earth Engine',
                    'GRASS GIS',
                    'PCI Geomatica',
                    'MATLAB Image Processing Toolbox',
                    'R (raster / terra)',
                    'OpenDroneMap',
                    'Agisoft Metashape',
                    'Pix4D',
                    'CloudCompare',
                    'QGIS (with plugins)',
                ],
                'فتوگرامتری' => [
                    'Agisoft Metashape',
                    'Pix4D',
                    'RealityCapture',
                    'Autodesk ReCap',
                    'ERDAS IMAGINE',
                    'Trimble Inpho',
                    'Leica Photogrammetry Suite',
                    'OpenDroneMap',
                    '3DF Zephyr',
                    'DroneDeploy',
                    'Bentley ContextCapture',
                    'CloudCompare',
                    'VisualSFM',
                    'IMAGINE Photogrammetry',
                    'SOCET GXP',
                ],
                'نقشه‌برداری زمینی' => [
                    'AutoCAD Civil 3D',
                    'Bentley MicroStation',
                    'Trimble Business Center',
                    'Leica Geo Office',
                    'STAR*NET',
                    'MicroSurvey CAD',
                    'Global Mapper',
                    'TOPCON Magnet',
                    'Sokkia Spectrum Survey',
                    'ArcGIS',
                    'QGIS',
                    'GeoPak (Bentley)',
                    'TerraModel',
                    'EZSurv',
                    'LandXML tools',
                ],
            ],

            // ── مهندسی هوافضا ────────────────────────────────────────────
            'مهندسی هوافضا' => [
                'آویونیک' => [
                    'MATLAB/Simulink',
                    'SCADE Suite (Ansys)',
                    'dSPACE',
                    'LabVIEW',
                    'Wind River VxWorks',
                    'IBM Rational DOORS',
                    'LDRA TBvision',
                    'VectorCAST',
                    'CANalyzer (Vector)',
                    'ETAS INCA',
                    'NI FlexRIO',
                    'Simulink Real-Time',
                    'AFDX/ARINC 664 tools',
                    'DO-178C toolchain',
                    'Green Hills INTEGRITY',
                ],
                'آیرودینامیک' => [
                    'ANSYS Fluent',
                    'ANSYS CFX',
                    'OpenFOAM',
                    'Simcenter STAR-CCM+',
                    'DATCOM (USAF)',
                    'XFOIL',
                    'AVL (Athena Vortex Lattice)',
                    'SU2 (Stanford)',
                    'VSAERO',
                    'PANAIR',
                    'OVERFLOW (NASA)',
                    'CFD++ (Metacomp)',
                    'Tecplot 360',
                    'ParaView',
                    'MATLAB',
                ],
                'پیشرانش' => [
                    'MATLAB/Simulink',
                    'ANSYS Fluent',
                    'CEA (NASA Chemical Equilibrium)',
                    'RocketCEA',
                    'NPSS (Numerical Propulsion System Simulation)',
                    'GasTurb',
                    'GT-POWER',
                    'OpenFOAM',
                    'CHEMKIN (Ansys)',
                    'Cantera',
                    'ABAQUS',
                    'ANSYS Mechanical',
                    'Tecplot 360',
                    'Simcenter STAR-CCM+',
                    'NUMECA FINE/Turbo',
                ],
                'سازه هوایی' => [
                    'MSC Nastran',
                    'ABAQUS',
                    'ANSYS Mechanical',
                    'HyperMesh (Altair)',
                    'OptiStruct (Altair)',
                    'CATIA',
                    'Siemens NX',
                    'ESACOMP (composites)',
                    'SAMCEF (Samtech)',
                    'ZAERO (aeroelasticity)',
                    'CAMRAD II (rotorcraft)',
                    'Nastran Aeroelastic',
                    'Dassault SIMULIA',
                    'Patran (MSC)',
                    'MATLAB',
                ],
            ],

            // ── میان‌رشته‌ای ──────────────────────────────────────────────
            'میان‌رشته‌ای' => [
                'انرژی تجدیدپذیر' => [
                    'HOMER Pro (NREL)',
                    'System Advisor Model (SAM, NREL)',
                    'RETScreen (NRCan)',
                    'PVsyst',
                    'WindPRO',
                    'WAsP',
                    'OpenDSS',
                    'ETAP',
                    'DIgSILENT PowerFactory',
                    'MATLAB/Simulink',
                    'TRNSYS',
                    'EnergyPlus',
                    'OpenFOAM (wind)',
                    'ANSYS Fluent',
                    'PSS/E',
                ],
                'بیوانفورماتیک' => [
                    'Python (Biopython)',
                    'R (Bioconductor)',
                    'BLAST (NCBI)',
                    'Clustal Omega',
                    'MEGA',
                    'Galaxy (bioinformatics platform)',
                    'GATK (Genome Analysis Toolkit)',
                    'Bowtie2 / BWA',
                    'SAMtools',
                    'AUGUSTUS (gene prediction)',
                    'HMMER',
                    'PyMOL',
                    'AutoDock Vina',
                    'Rosetta',
                    'MATLAB Bioinformatics Toolbox',
                ],
                'فناوری نانو' => [
                    'Materials Studio (BIOVIA)',
                    'LAMMPS',
                    'GROMACS',
                    'VASP',
                    'Quantum ESPRESSO',
                    'Gaussian',
                    'COMSOL Multiphysics (MEMS/Nano)',
                    'NAMD',
                    'VMD (Visual Molecular Dynamics)',
                    'VESTA',
                    'Gwyddion (SPM analysis)',
                    'ImageJ / Fiji',
                    'OriginPro',
                    'Avogadro',
                    'NanoHub simulation tools',
                ],
                'مکاترونیک' => [
                    'MATLAB/Simulink',
                    'LabVIEW',
                    'SolidWorks',
                    'CATIA',
                    'ANSYS Mechanical',
                    'ANSYS Twin Builder',
                    'Modelica / OpenModelica',
                    'MSC Adams',
                    'ROS (Robot Operating System)',
                    'Siemens TIA Portal',
                    'Allen-Bradley Studio 5000',
                    'dSPACE',
                    'Arduino IDE',
                    'Altium Designer',
                    'Beckhoff TwinCAT',
                ],
            ],

        ];

        // ─────────────────────────────────────────────────────────────────
        // Pre-load domain and subdomain lookups (single queries)
        // ─────────────────────────────────────────────────────────────────
        $domainMap = DB::table('skill_domains')
            ->pluck('id', 'name')
            ->toArray();

        $subdomainRows = DB::table('subdomains')
            ->select('id', 'name', 'skill_domain_id')
            ->get();

        // key: "{domain_id}|{subdomain_name}" => subdomain_id
        $subLookup = [];
        foreach ($subdomainRows as $row) {
            $subLookup["{$row->skill_domain_id}|{$row->name}"] = $row->id;
        }

        // ─────────────────────────────────────────────────────────────────
        // Insert skills
        // ─────────────────────────────────────────────────────────────────
        $inserted = 0;
        $skipped  = 0;

        foreach ($taxonomy as $domainName => $subdomains) {
            $domainId = $domainMap[$domainName] ?? null;

            if (! $domainId) {
                $this->command->warn("  [SKIP] Domain not found: \"{$domainName}\"");
                continue;
            }

            foreach ($subdomains as $subdomainName => $skills) {
                $subdomainId = $subLookup["{$domainId}|{$subdomainName}"] ?? null;

                if (! $subdomainId) {
                    $this->command->warn("  [SKIP] Subdomain not found: \"{$domainName} > {$subdomainName}\"");
                    continue;
                }

                foreach (array_unique($skills) as $skillName) {
                    $exists = DB::table('skills')
                        ->where('name', $skillName)
                        ->where('subdomain_id', $subdomainId)
                        ->exists();

                    if (! $exists) {
                        DB::table('skills')->insert([
                            'id'           => (string) Str::uuid(),
                            'name'         => $skillName,
                            'subdomain_id' => $subdomainId,
                            'process_id'   => null,
                            'created_at'   => now(),
                            'updated_at'   => now(),
                        ]);
                        $inserted++;
                    } else {
                        $skipped++;
                    }
                }
            }
        }

        $this->command->info("  EngineeringSkillsSeeder: {$inserted} inserted, {$skipped} already existed.");
    }
}
