<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>EngiPi — مارکت‌پلیس تخصصی مهندسی</title>
  <meta name="description" content="متخصص مهندسی مناسب پروژه‌تان را براساس حوزه، مهارت و تجربه پیدا کنید.">
  <link rel="stylesheet" href="{{ asset('vendor/engipi/fonts/remixicon.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/engipi/fonts/vazirmatn.css') }}">
  <link rel="stylesheet" href="{{ asset('vendor/engipi/css/blueprint.css') }}">
  <style>
  :root{--n:#06111f;--n2:#0a192b;--panel:#0d1d30;--blue:#2f74ff;--blue-h:#1f63ea;--cyan:#43c8d6;--text:#f7faff;--muted:#a7b5c7;--line:rgba(170,197,226,.16);--container:1180px}
  *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-width:320px;overflow-x:hidden;background:var(--n);color:var(--text);font-family:Vazirmatn,Tahoma,sans-serif}button,a{font:inherit}a{color:inherit;text-decoration:none}.v2-container{width:min(calc(100% - 40px),var(--container));margin-inline:auto}
  .v2-shell{position:relative;min-height:100vh;overflow:hidden;background:linear-gradient(rgba(89,137,188,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(89,137,188,.055) 1px,transparent 1px),var(--n);background-size:42px 42px}.v2-shell:before{position:absolute;inset:0;pointer-events:none;background:linear-gradient(90deg,var(--n),transparent 25%,transparent 75%,var(--n));content:""}
  .v2-header{position:relative;z-index:20;border-bottom:1px solid var(--line);background:rgba(6,17,31,.94)}.v2-nav{display:grid;grid-template-columns:auto 1fr auto;min-height:78px;align-items:center;gap:32px}.v2-brand{display:inline-flex;align-items:center;gap:10px;font-size:1.38rem;font-weight:900;letter-spacing:-.04em}.v2-brand em{color:#76a5ff;font-style:normal}.v2-mark{position:relative;display:grid;width:38px;height:38px;place-items:center;border:1px solid rgba(77,139,255,.7);border-radius:10px;font-family:Arial,sans-serif;font-size:.8rem;font-weight:800}.v2-mark:after{position:absolute;inset:5px;border:1px solid rgba(67,200,214,.34);border-radius:6px;content:""}
  .v2-links{display:flex;align-items:center;justify-content:center;gap:2px;margin:0;padding:0;list-style:none}.v2-links a{display:block;padding:9px 11px;border-radius:8px;color:#c5d0de;font-size:.87rem;font-weight:600;transition:.18s}.v2-links a:hover,.v2-links a:focus-visible{background:rgba(47,116,255,.1);color:#fff;outline:0}.v2-actions{display:flex;align-items:center;gap:10px}.v2-login{padding:10px 5px;color:#d5deea;font-size:.88rem;font-weight:700}.v2-login:hover{color:#fff}
  .v2-btn{display:inline-flex;min-height:46px;align-items:center;justify-content:center;gap:8px;padding:10px 18px;border:1px solid transparent;border-radius:9px;cursor:pointer;font-weight:800;transition:background .18s,border-color .18s,transform .18s}.v2-btn:hover{transform:translateY(-1px)}.v2-btn:focus-visible{outline:3px solid rgba(91,151,255,.35);outline-offset:3px}.v2-primary{border-color:var(--blue);background:var(--blue);color:#fff}.v2-primary:hover{border-color:var(--blue-h);background:var(--blue-h)}.v2-secondary{border-color:rgba(178,202,228,.26);background:transparent;color:#eef5ff}.v2-secondary:hover{border-color:rgba(178,202,228,.45);background:rgba(255,255,255,.04)}.v2-toggle{display:none;width:44px;height:44px;align-items:center;justify-content:center;border:1px solid var(--line);border-radius:9px;background:transparent;color:#fff;cursor:pointer;font-size:1.35rem}
  .v2-hero{position:relative;z-index:2}.v2-hero-grid{display:grid;grid-template-columns:minmax(0,1.04fr) minmax(380px,.96fr);min-height:calc(100vh - 79px);align-items:center;gap:clamp(48px,7vw,90px);padding-block:76px 88px}.v2-copy{max-width:650px}.v2-kicker{display:inline-flex;align-items:center;gap:9px;margin-bottom:22px;color:#89b1ff;font-size:.83rem;font-weight:800}.v2-kicker:before{width:30px;height:2px;background:var(--blue);content:""}.v2-title{margin:0 0 22px;color:#fff;font-size:clamp(2.55rem,5.25vw,4.65rem);font-weight:950;letter-spacing:-.055em;line-height:1.22}.v2-title span{display:block;margin-top:5px;color:#80aaff}.v2-desc{max-width:610px;margin:0 0 30px;color:var(--muted);font-size:clamp(1rem,1.4vw,1.12rem);line-height:2}.v2-hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:32px}.v2-hero-actions .v2-btn{min-height:52px;padding-inline:22px}.v2-trust{display:flex;flex-wrap:wrap;gap:12px 22px;margin:0;padding:0;list-style:none}.v2-trust li{display:flex;align-items:center;gap:7px;color:#aebdce;font-size:.84rem;font-weight:600}.v2-trust i{color:var(--cyan);font-size:1.05rem}
  .v2-visual{position:relative;width:100%;max-width:520px;justify-self:end}.v2-visual:before{position:absolute;top:-26px;inset-inline-start:-28px;width:80px;height:80px;border-top:1px solid rgba(67,200,214,.32);border-inline-start:1px solid rgba(67,200,214,.32);content:""}.v2-project{position:relative;padding:clamp(24px,3vw,34px);border:1px solid rgba(151,181,214,.2);border-radius:18px;background:var(--panel);box-shadow:0 24px 60px rgba(0,0,0,.3)}.v2-card-top{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:22px}.v2-status{display:inline-flex;align-items:center;gap:7px;color:#b9c8d9;font-size:.76rem;font-weight:700}.v2-status:before{width:7px;height:7px;border-radius:50%;background:var(--cyan);content:""}.v2-code{color:#60738a;font-family:ui-monospace,monospace;font-size:.72rem;direction:ltr}.v2-project h2{margin:0 0 14px;color:#fff;font-size:clamp(1.22rem,2vw,1.52rem);line-height:1.55}.v2-tags{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px}.v2-tag{padding:6px 10px;border:1px solid rgba(91,151,255,.22);border-radius:7px;background:rgba(47,116,255,.075);color:#aec8fa;font-size:.72rem;font-weight:700}.v2-project p{margin:0 0 24px;color:#9eafc1;font-size:.9rem;line-height:1.9}
  .v2-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;overflow:hidden;margin-bottom:22px;border:1px solid var(--line);border-radius:10px;background:var(--line)}.v2-meta>div{min-width:0;padding:13px 12px;background:#0a192a}.v2-meta span{display:block;margin-bottom:6px;color:#6f8298;font-size:.68rem}.v2-meta strong{display:block;color:#edf4fc;font-size:.78rem;line-height:1.55}.v2-experts{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:22px}.v2-avatars{display:flex;align-items:center;direction:ltr}.v2-avatar{width:36px;height:36px;margin-left:-8px;border:2px solid var(--panel);border-radius:50%;object-fit:cover}.v2-avatar:first-child{margin-left:0}.v2-expert-copy{color:#9cadbf;font-size:.77rem;line-height:1.6;text-align:end}.v2-expert-copy strong{display:block;color:#fff;font-size:.86rem}.v2-project .v2-btn{width:100%}.v2-note{position:absolute;right:-34px;bottom:42px;display:flex;align-items:center;gap:8px;padding:9px 12px;border:1px solid rgba(67,200,214,.23);border-radius:8px;background:#071523;color:#a9bbc9;font-size:.7rem;box-shadow:0 12px 26px rgba(0,0,0,.25)}.v2-note i{color:var(--cyan)}
  /* Refined dark Header + Hero */
  body{background:#f7f9fc;color:#10233f}
  .v2-shell{min-height:0;background:radial-gradient(circle at 78% 46%,rgba(47,116,255,.095),transparent 30%),linear-gradient(118deg,#06111f 0%,#08172a 52%,#09203a 100%);isolation:isolate}
  .v2-shell:before{z-index:-1;background:linear-gradient(rgba(103,150,202,.026) 1px,transparent 1px),linear-gradient(90deg,rgba(103,150,202,.026) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.7),transparent 92%)}
  .v2-shell:after{position:absolute;z-index:-1;top:118px;left:5%;width:310px;height:210px;pointer-events:none;border-top:1px solid rgba(101,152,211,.08);border-left:1px solid rgba(101,152,211,.08);background:linear-gradient(135deg,transparent 49.7%,rgba(101,152,211,.055) 50%,transparent 50.3%);content:"";transform:skewY(-5deg)}
  .v2-header{position:sticky;top:0;border-bottom-color:rgba(166,194,225,.13);background:#071321;box-shadow:0 1px 0 rgba(0,0,0,.16)}
  .v2-nav{min-height:66px;gap:26px}.v2-brand{font-size:1.28rem}.v2-mark{width:35px;height:35px;border-color:rgba(91,151,255,.55);background:#0a1a2c}.v2-brand em{color:#77a4ff}
  .v2-links a{color:#b5c2d2}.v2-links a:hover,.v2-links a:focus-visible{background:rgba(47,116,255,.1);color:#fff}
  .v2-login{color:#c9d4e1}.v2-login:hover{color:#fff}.v2-toggle{border-color:rgba(170,197,226,.18);background:#0a192b;color:#fff}
  .v2-btn{min-height:46px;padding:10px 19px}.v2-primary{border-color:#3478f6;background:#3478f6}.v2-primary:hover{border-color:#2869dc;background:#2869dc}
  .v2-secondary{border-color:rgba(190,211,234,.42);background:rgba(255,255,255,.015);color:#f2f7fd}.v2-secondary:hover{border-color:rgba(190,211,234,.65);background:rgba(255,255,255,.055)}
  .v2-hero-grid{grid-template-columns:minmax(0,1.3fr) minmax(370px,1fr);min-height:min(630px,calc(100svh - 98px));gap:clamp(28px,4vw,50px);padding-block:40px 44px}
  .v2-copy{max-width:630px}.v2-kicker{margin-bottom:15px;color:#8fb2f6}.v2-title{margin-bottom:17px;font-size:clamp(2.25rem,4.15vw,3.55rem);letter-spacing:-.045em;line-height:1.13}.v2-title span{margin-top:3px;color:#78a5f8;text-shadow:0 7px 28px rgba(47,116,255,.12)}.v2-desc{max-width:560px;margin-bottom:23px;color:#aebccc;font-size:clamp(.93rem,1.15vw,1.04rem);line-height:1.85}
  .v2-hero-actions{gap:11px;margin-bottom:23px}.v2-hero-actions .v2-btn{min-height:48px;padding-inline:20px}.v2-hero-actions i{font-size:1.08rem}
  .v2-trust{gap:10px 24px}.v2-trust li{gap:8px;color:#aebccc;font-size:.8rem}.v2-trust i{display:grid;width:25px;height:25px;place-items:center;border-radius:50%;background:rgba(67,200,214,.08);color:#55c4d0;font-size:1rem}
  .v2-visual{max-width:500px}.v2-visual:before{top:-15px;inset-inline-start:-16px;width:64px;height:64px;border-color:rgba(67,200,214,.2)}
  .v2-project{padding:25px;border-color:rgba(157,187,219,.22);border-radius:16px;background:linear-gradient(155deg,#10233a,#0b1b2e);box-shadow:0 20px 48px rgba(0,0,0,.27),0 0 0 1px rgba(255,255,255,.015) inset}
  .v2-card-top{margin-bottom:16px}.v2-status{color:#c0ccda}.v2-status:before{background:#43c8d6}.v2-code{color:#74879d}.v2-project h2{margin-bottom:11px;color:#fff;font-size:clamp(1.15rem,1.7vw,1.38rem);line-height:1.45}
  .v2-tags{gap:6px;margin-bottom:15px}.v2-tag{padding:5px 9px;border-color:rgba(103,155,255,.23);background:rgba(47,116,255,.09);color:#b7cdf8}.v2-project p{margin-bottom:18px;color:#aebccc;font-size:.84rem;line-height:1.8}
  .v2-meta{gap:6px;margin-bottom:17px;border:0;background:transparent}.v2-meta>div{padding:11px;border:1px solid rgba(160,190,220,.12);border-radius:9px;background:rgba(5,15,27,.32)}.v2-meta span{margin-bottom:4px;color:#8295aa}.v2-meta strong{color:#edf4fc;font-size:.74rem}
  .v2-experts{margin-bottom:17px}.v2-avatar{width:34px;height:34px;border-color:#10233a}.v2-expert-copy{color:#9fb0c2}.v2-expert-copy strong{color:#fff}.v2-project>.v2-btn{min-height:47px;margin-top:2px}
  .v2-light-transition{position:relative;height:56px;border-radius:28px 28px 0 0;background:#f7f9fc;box-shadow:0 -12px 28px rgba(2,10,20,.09)}
  @media(max-width:1080px){.v2-nav{gap:16px}.v2-links a{padding-inline:7px;font-size:.8rem}.v2-hero-grid{grid-template-columns:minmax(0,1.18fr) minmax(350px,.92fr);gap:30px}.v2-title{font-size:clamp(2.15rem,4vw,3.15rem)}.v2-project{padding:21px}}
  @media(max-width:900px){.v2-toggle{display:inline-flex;justify-self:end}.v2-links{position:absolute;top:calc(100% + 1px);inset-inline:20px;display:none;align-items:stretch;padding:12px;border:1px solid var(--line);border-radius:12px;background:#0a192b;box-shadow:0 18px 40px rgba(0,0,0,.28)}.v2-links.open{display:grid}.v2-links a{padding:11px 12px}.v2-actions{justify-self:center}.v2-hero-grid{grid-template-columns:minmax(0,1.08fr) minmax(320px,.92fr);min-height:620px;gap:24px;padding-block:36px 42px}.v2-title{font-size:clamp(2rem,4.8vw,2.7rem)}.v2-desc{font-size:.9rem}.v2-trust{gap:9px 14px}.v2-project{padding:18px}.v2-meta{grid-template-columns:1fr}.v2-meta>div{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 10px}.v2-meta span{margin:0}}
  @media(max-width:720px){.v2-hero-grid{grid-template-columns:1fr;min-height:0;gap:34px;padding-block:38px 46px}.v2-copy{max-width:620px}.v2-visual{max-width:540px;justify-self:center}}
  @media(max-width:640px){.v2-container{width:min(calc(100% - 28px),var(--container))}.v2-nav{min-height:62px;gap:9px}.v2-brand{font-size:1.14rem}.v2-mark{width:32px;height:32px}.v2-actions .v2-btn{display:none}.v2-login{padding-inline:0;font-size:.78rem}.v2-title{font-size:clamp(2rem,10vw,2.75rem);line-height:1.17}.v2-kicker{margin-bottom:13px}.v2-desc{margin-bottom:20px;line-height:1.8}.v2-hero-grid{padding-block:32px 40px}.v2-hero-actions{display:grid;grid-template-columns:1fr;margin-bottom:20px}.v2-hero-actions .v2-btn{width:100%}.v2-trust{display:grid;grid-template-columns:1fr 1fr;gap:9px}.v2-project{padding:19px 16px;border-radius:14px}.v2-experts{align-items:flex-end}.v2-visual:before{display:none}.v2-light-transition{height:38px;border-radius:20px 20px 0 0}}
  @media(max-width:390px){.v2-trust{grid-template-columns:1fr}.v2-experts{align-items:flex-start;flex-direction:column}.v2-expert-copy{text-align:start}}
  @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*:before,*:after{transition-duration:.01ms!important}}
  </style>
</head>
<body>
<div class="v2-shell">
<header class="v2-header"><nav class="v2-container v2-nav" aria-label="ناوبری اصلی">
  <a class="v2-brand" href="{{ route('landing.v2') }}" aria-label="EngiPi، صفحه اصلی نسخه دوم"><span class="v2-mark" aria-hidden="true">EP</span><span><em>Eng</em>iPi</span></a>
  <ul class="v2-links" id="v2Menu">
    <li><a href="{{ route('root') }}#projects">پروژه‌ها</a></li><li><a href="{{ route('root') }}#specialists">متخصصان</a></li><li><a href="{{ route('root') }}#domains">حوزه‌های مهندسی</a></li><li><a href="{{ route('root') }}#how">چطور کار می‌کند؟</a></li><li><a href="{{ route('about') }}">درباره ما</a></li>
  </ul>
  <div class="v2-actions"><a class="v2-login" href="{{ route('login') }}">ورود / ثبت‌نام</a><a class="v2-btn v2-primary" href="{{ route('guest.project') }}">ثبت پروژه</a><button class="v2-toggle" type="button" aria-label="باز کردن منو" aria-controls="v2Menu" aria-expanded="false"><i class="ri-menu-3-line" aria-hidden="true"></i></button></div>
</nav></header>
<main><section class="v2-hero" aria-labelledby="v2Title"><div class="v2-container v2-hero-grid">
  <div class="v2-copy"><span class="v2-kicker">بازار تخصصی خدمات مهندسی</span><h1 class="v2-title" id="v2Title">پروژه مهندسی داری؟<span>متخصص مناسبش همین‌جاست.</span></h1><p class="v2-desc">از طراحی و تحلیل تا شبیه‌سازی و اجرای پروژه؛ متخصصان مهندسی را بر اساس حوزه، مهارت و تجربه پیدا کن و بهترین نتیجه را بگیر.</p>
    <div class="v2-hero-actions"><a class="v2-btn v2-primary" href="{{ route('guest.project') }}"><i class="ri-add-circle-line" aria-hidden="true"></i>ثبت رایگان پروژه</a><a class="v2-btn v2-secondary" href="{{ route('register') }}"><i class="ri-user-search-line" aria-hidden="true"></i>پیدا کردن متخصص</a></div>
    <ul class="v2-trust" aria-label="مزایای EngiPi"><li><i class="ri-verified-badge-line" aria-hidden="true"></i>متخصصان تأییدشده</li><li><i class="ri-chat-1-line" aria-hidden="true"></i>ارتباط مستقیم</li><li><i class="ri-shield-check-line" aria-hidden="true"></i>پرداخت امن</li></ul>
  </div>
  <div class="v2-visual" aria-label="نمونه پروژه در بازار EngiPi"><article class="v2-project"><div class="v2-card-top"><span class="v2-status">آماده دریافت پیشنهاد</span><span class="v2-code">PROJECT / 0218</span></div><h2>طراحی و تحلیل سازه صنعتی</h2><div class="v2-tags"><span class="v2-tag">مهندسی مکانیک</span><span class="v2-tag">SolidWorks</span><span class="v2-tag">ANSYS</span></div><p>طراحی و تحلیل یک سازه فلزی صنعتی به همراه ارائه نقشه‌های اجرایی و گزارش محاسبات.</p>
    <div class="v2-meta"><div><span>بودجه پروژه</span><strong>۱۵ تا ۲۵ میلیون تومان</strong></div><div><span>زمان تحویل</span><strong>۳۰ روز</strong></div><div><span>تطابق تخصصی</span><strong>۱۲ متخصص</strong></div></div>
    <div class="v2-experts"><div class="v2-avatars" aria-label="نمونه متخصصان مرتبط"><img class="v2-avatar" src="{{ asset('build/images/users/avatar-2.jpg') }}" alt="متخصص مهندسی"><img class="v2-avatar" src="{{ asset('build/images/users/avatar-5.jpg') }}" alt="متخصص مهندسی"><img class="v2-avatar" src="{{ asset('build/images/users/avatar-7.jpg') }}" alt="متخصص مهندسی"><img class="v2-avatar" src="{{ asset('build/images/users/avatar-8.jpg') }}" alt="متخصص مهندسی"></div><div class="v2-expert-copy"><strong>۱۲ متخصص مرتبط</strong>براساس مهارت و تجربه</div></div>
    <a class="v2-btn v2-primary" href="{{ route('register') }}">مشاهده متخصصان مرتبط</a></article></div>
</div></section></main><div class="v2-light-transition" aria-hidden="true"></div>
</div>
<script>document.addEventListener('DOMContentLoaded',function(){const t=document.querySelector('.v2-toggle'),m=document.getElementById('v2Menu');if(!t||!m)return;function close(){m.classList.remove('open');t.setAttribute('aria-expanded','false');t.setAttribute('aria-label','باز کردن منو');t.querySelector('i').className='ri-menu-3-line'}t.addEventListener('click',function(){const o=m.classList.toggle('open');t.setAttribute('aria-expanded',o?'true':'false');t.setAttribute('aria-label',o?'بستن منو':'باز کردن منو');t.querySelector('i').className=o?'ri-close-line':'ri-menu-3-line'});m.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('click',e=>{if(!m.contains(e.target)&&!t.contains(e.target))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();t.focus()}});window.addEventListener('resize',()=>{if(innerWidth>900)close()})});</script>
</body></html>
