<?php

return [
    'base_path' => '/assets/skill-icons/',
    'generic' => ['icon_path' => 'fallback-engineering.svg', 'fallback_category' => 'engineering', 'level' => 4],
    'field' => ['icon_path' => 'fallback-field.svg', 'fallback_category' => 'field', 'level' => 3],

    // Admin-friendly aliases: names resolve to one local asset and fallback category.
    'entries' => [
        ['names'=>['Revit Structure','Revit'],'icon_path'=>'revit.svg','fallback_category'=>'architecture','level'=>1],
        ['names'=>['ArchiCAD','Archi CAD'],'icon_path'=>'archicad.svg','fallback_category'=>'architecture','level'=>1],
        ['names'=>['AutoCAD Civil 3D','AutoCAD Electrical','AutoCAD Mechanical','AutoCAD Plant 3D','AutoCAD P&ID','AutoCAD'],'icon_path'=>'autocad.svg','fallback_category'=>'cad','level'=>1],
        ['names'=>['SketchUp','Sketch Up'],'icon_path'=>'sketchup.svg','fallback_category'=>'architecture','level'=>1],
        ['names'=>['Rhinoceros','Rhino 3D','Rhino','Grasshopper'],'icon_path'=>'rhino.svg','fallback_category'=>'cad','level'=>1],
        ['names'=>['MATLAB/Simulink','MATLAB'],'icon_path'=>'matlab.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Python (SciPy)','Python (pandas)','Python (Biopython)','Python (Scapy)','Python'],'icon_path'=>'python.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['ANSYS Mechanical','ANSYS Fluent','ANSYS CFX','ANSYS CFD','ANSYS'],'icon_path'=>'ansys.svg','fallback_category'=>'simulation','level'=>1],
        ['names'=>['COMSOL Multiphysics','COMSOL'],'icon_path'=>'comsol.svg','fallback_category'=>'simulation','level'=>1],
        ['names'=>['Abaqus/CAE','Abaqus'],'icon_path'=>'abaqus.svg','fallback_category'=>'simulation','level'=>1],
        ['names'=>['LabVIEW'],'icon_path'=>'labview.svg','fallback_category'=>'electronics','level'=>1],
        ['names'=>['Altium Designer','Altium'],'icon_path'=>'altium.svg','fallback_category'=>'electronics','level'=>1],
        ['names'=>['KiCad'],'icon_path'=>'kicad.svg','fallback_category'=>'electronics','level'=>1],
        ['names'=>['MIMICS','Materialise Mimics','Mimics Innovation Suite'],'icon_path'=>'materialise.svg','fallback_category'=>'biomedical','level'=>1],
        ['names'=>['OpenSim'],'icon_path'=>'opensim.svg','fallback_category'=>'biomedical','level'=>1],
        ['names'=>['BIOPAC Student Lab','BIOPAC'],'icon_path'=>'biopac.svg','fallback_category'=>'biomedical','level'=>1],
        ['names'=>['AnyBody Modeling System','AnyBody'],'icon_path'=>'anybody.svg','fallback_category'=>'biomedical','level'=>2],
        ['names'=>['SAP2000 Nonlinear','SAP 2000 Nonlinear','SAP2000','SAP 2000','ETABS Nonlinear','ETABS','SAFE','PERFORM-3D'],'icon_path'=>'csi.svg','fallback_category'=>'structural','level'=>2],
        ['names'=>['Proteus Design Suite','Proteus'],'icon_path'=>'labcenter.svg','fallback_category'=>'electronics','level'=>2],
        ['names'=>['Multisim'],'icon_path'=>'ni.svg','fallback_category'=>'electronics','level'=>2],
        ['names'=>['LTspice','LT spice'],'icon_path'=>'analog-devices.svg','fallback_category'=>'electronics','level'=>2],
        ['names'=>['SOLIDWORKS Medical','SOLIDWORKS CAM','SOLIDWORKS','Solid Works','CATIA Manufacturing','CATIA','SIMULIA'],'icon_path'=>'dassault-systemes.svg','fallback_category'=>'manufacturing','level'=>2],
        ['names'=>['Autodesk 3ds Max','3ds Max','Autodesk Inventor','Fusion 360','Navisworks','ROBOT Structural','BIM 360','Moldflow','PowerMill'],'icon_path'=>'autodesk.svg','fallback_category'=>'cad','level'=>2],
        ['names'=>['STAAD.Pro','STAAD Pro','OpenRoads','WaterGEMS','Synchro 4D','Synchro','PLAXIS 2D/3D','PLAXIS'],'icon_path'=>'bentley.svg','fallback_category'=>'structural','level'=>2],
        ['names'=>['Siemens NX CAE','Siemens NX CAM','Siemens NX','TIA Portal','WinCC','PLC Programming','Simcenter Testlab','PSS/E'],'icon_path'=>'siemens.svg','fallback_category'=>'engineering','level'=>2],
        ['names'=>['QGIS','GRASS GIS'],'icon_path'=>'qgis.svg','fallback_category'=>'gis','level'=>1],
        ['names'=>['Arduino'],'icon_path'=>'arduino.svg','fallback_category'=>'electronics','level'=>1],
        ['names'=>['Blender'],'icon_path'=>'blender.svg','fallback_category'=>'cad','level'=>1],
        ['names'=>['Power BI'],'icon_path'=>'powerbi.svg','fallback_category'=>'data','level'=>2],
        ['names'=>['Tableau'],'icon_path'=>'tableau.svg','fallback_category'=>'data','level'=>2],
        ['names'=>['Google Earth Engine','Google Earth Pro'],'icon_path'=>'googleearth.svg','fallback_category'=>'gis','level'=>2],
        ['names'=>['CUDA','Xilinx Vitis HLS'],'icon_path'=>'nvidia.svg','fallback_category'=>'programming','level'=>2],
        ['names'=>['Quartus Prime','Quartus'],'icon_path'=>'intel.svg','fallback_category'=>'electronics','level'=>2],
        ['names'=>['Tekla Structures','Trimble'],'icon_path'=>'trimble.svg','fallback_category'=>'cad','level'=>2],
        ['names'=>['MS Project','Microsoft Project'],'icon_path'=>'microsoft.svg','fallback_category'=>'project','level'=>2],
        ['names'=>['Cisco Packet Tracer'],'icon_path'=>'cisco.svg','fallback_category'=>'network','level'=>2],
        ['names'=>['C++','C'],'icon_path'=>'cplusplus.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['JavaScript'],'icon_path'=>'javascript.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Java'],'icon_path'=>'java.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['R Programming','R language','R'],'icon_path'=>'r.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Node.js'],'icon_path'=>'nodejs.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Django'],'icon_path'=>'django.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Laravel'],'icon_path'=>'laravel.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['React'],'icon_path'=>'react.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['PyTorch'],'icon_path'=>'pytorch.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['TensorFlow'],'icon_path'=>'tensorflow.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Scikit-learn'],'icon_path'=>'scikitlearn.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['OpenCV'],'icon_path'=>'opencv.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Docker'],'icon_path'=>'docker.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Kubernetes'],'icon_path'=>'kubernetes.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Terraform'],'icon_path'=>'terraform.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Git'],'icon_path'=>'git.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Linux'],'icon_path'=>'linux.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Raspberry Pi'],'icon_path'=>'raspberry-pi.svg','fallback_category'=>'electronics','level'=>1],
        ['names'=>['Wireshark'],'icon_path'=>'wireshark.svg','fallback_category'=>'network','level'=>1],
        ['names'=>['ROS'],'icon_path'=>'ros.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['LLVM'],'icon_path'=>'llvm.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Ansible'],'icon_path'=>'ansible.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Apache Airflow','Airflow'],'icon_path'=>'airflow.svg','fallback_category'=>'data','level'=>1],
        ['names'=>['Apache Spark'],'icon_path'=>'spark.svg','fallback_category'=>'data','level'=>1],
        ['names'=>['Eclipse'],'icon_path'=>'eclipse.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['Burp Suite'],'icon_path'=>'burpsuite.svg','fallback_category'=>'network','level'=>1],
        ['names'=>['Metasploit'],'icon_path'=>'metasploit.svg','fallback_category'=>'network','level'=>1],
        ['names'=>['Hugging Face'],'icon_path'=>'huggingface.svg','fallback_category'=>'data','level'=>1],
        ['names'=>['Kali Linux'],'icon_path'=>'linux.svg','fallback_category'=>'programming','level'=>1],
        ['names'=>['SAP ERP','SAP SCM'],'icon_path'=>'sap.svg','fallback_category'=>'data','level'=>2],
    ],

    'categories' => [
        ['name'=>'biomedical','keywords'=>['mimics','materialise','anybody','opensim','biopac','biomedical','medical','biomechanic','tissue','eeg','ecg'],'icon_path'=>'fallback-biomedical.svg','level'=>3],
        ['name'=>'hdl','keywords'=>['vhdl','verilog','systemverilog','modelsim','model sim','hdl'],'icon_path'=>'fallback-hdl.svg','level'=>3],
        ['name'=>'structural','keywords'=>['staad','safe','etabs','sap2000','sap 2000','perform 3d','opensees','seismosoft','structural','stresscheck'],'icon_path'=>'fallback-structural.svg','level'=>3],
        ['name'=>'architecture','keywords'=>['revit','archicad','sketchup','lumion','enscape','v ray','space syntax','cityengine'],'icon_path'=>'architecture.svg','level'=>3],
        ['name'=>'manufacturing','keywords'=>['manufacturing','cam','cnc','mastercam','solidworks','catia','powermill'],'icon_path'=>'fallback-cad.svg','level'=>3],
        ['name'=>'cad','keywords'=>['cad','inventor','creo','tekla','navisworks','civil 3d','plant 3d','rhino','3ds max','modeling','drawing'],'icon_path'=>'fallback-cad.svg','level'=>3],
        ['name'=>'electronics','keywords'=>['kicad','altium','cadence','orcad','proteus','multisim','ltspice','quartus','vivado','fpga','plc','scada','eplan','pscad','psim','plecs','circuit','modbus','opc ua'],'icon_path'=>'fallback-electronics.svg','level'=>3],
        ['name'=>'programming','keywords'=>['python','javascript','java','django','laravel','react','node','sql','programming','tensorflow','pytorch','scikit','opencv','cuda','c plus plus'],'icon_path'=>'fallback-programming.svg','level'=>3],
        ['name'=>'simulation','keywords'=>['ansys','abaqus','comsol','fluent','cfx','simulation','simulink','nastran','dyna','openfoam','cfd','fea','adams','anylogic','flexsim','arena','star ccm','lammps'],'icon_path'=>'fallback-simulation.svg','level'=>3],
        ['name'=>'gis','keywords'=>['gis','arcgis','map','earth','envi','erdas','photogrammetry','pix4d','metashape','geosoft','leica','gnss'],'icon_path'=>'fallback-gis.svg','level'=>3],
        ['name'=>'data','keywords'=>['excel','power bi','tableau','spss','minitab','origin','data','spark','airflow','dbt','jmp','mlflow'],'icon_path'=>'fallback-data.svg','level'=>3],
        ['name'=>'network','keywords'=>['network','wireshark','nmap','gns3','packet tracer','ns 3','qemu','metasploit','burp'],'icon_path'=>'fallback-network.svg','level'=>3],
        ['name'=>'project','keywords'=>['project','primavera','lean','vsm','spc tools'],'icon_path'=>'fallback-project.svg','level'=>3],
        ['name'=>'geoscience','keywords'=>['mining','mine','surpac','vulcan','datamine','leapfrog','flac','3dec','udec','geostudio','plaxis','petrel'],'icon_path'=>'fallback-geoscience.svg','level'=>3],
    ],
];